# Generated by Django 4.2.15 on 2024-08-30 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(unique=True)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotkey', models.CharField(max_length=255)),
                ('is_mother', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discord_id', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('ssh_private_key', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('operators', models.ManyToManyField(blank=True, related_name='subnets', to='manager.operator')),
            ],
        ),
        migrations.CreateModel(
            name='SubnetSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchain', models.CharField(choices=[('mainnet', 'Mainnet'), ('testnet', 'Testnet')], max_length=50)),
                ('netuid', models.IntegerField()),
                ('restart_threshold', models.IntegerField(default=0)),
                ('reinstall_threshold', models.IntegerField(default=0)),
                ('deregistration_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deregistration_slots', to='manager.block')),
                ('registration_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_slots', to='manager.block')),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='manager.subnet')),
            ],
        ),
        migrations.CreateModel(
            name='ValidatorInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('uses_child_hotkey', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotkey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.hotkey')),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validator_instances', to='manager.server')),
                ('subnet_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validator_instances', to='manager.subnetslot')),
            ],
        ),
    ]
