# Generated by Django 4.2.15 on 2024-09-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='id',
        ),
        migrations.AddField(
            model_name='subnet',
            name='running_mainnet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subnet',
            name='running_testnet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='block',
            name='serial_number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
