# Generated by Django 4.2.15 on 2024-09-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_remove_block_id_subnet_running_mainnet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnetslot',
            name='maximum_registration_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subnetslot',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
