# Generated by Django 4.2.15 on 2024-09-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_block_hotkey_operator_server_subnet_subnetslot_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subnetslot",
            old_name="registered",
            new_name="registered_status",
        ),
        migrations.AlterField(
            model_name="validatorinstance",
            name="last_updated",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
