# Generated by Django 4.2.15 on 2024-09-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_registered_subnetslot_registered_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subnetslot",
            name="registered_status",
        ),
        migrations.AddField(
            model_name="subnetslot",
            name="is_registered",
            field=models.BooleanField(
                default=False, help_text="Indicates if the slot is registered (in blocks of unset weights)"
            ),
        ),
        migrations.AlterField(
            model_name="subnetslot",
            name="maximum_registration_price",
            field=models.IntegerField(default=0, help_text="Maximum registration price in RAO"),
        ),
    ]
