# Generated by Django 4.2.15 on 2024-09-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_subnet_operators_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subnet",
            name="operators",
            field=models.ManyToManyField(blank=True, related_name="subnets", to="core.operator"),
        ),
    ]
