# Generated by Django 4.2.15 on 2024-09-03 02:42

import django.db.models.deletion
from django.db import migrations, models

import auto_validator.core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_subnetslot_registered_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotkey",
            name="hotkey",
            field=models.CharField(max_length=48, validators=[auto_validator.core.models.validate_hotkey_length]),
        ),
        migrations.AlterField(
            model_name="subnetslot",
            name="subnet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slots",
                to="core.subnet",
            ),
        ),
    ]
