# Generated by Django 4.2.16 on 2024-09-13 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_validatorinstance_server_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedfile",
            name="user",
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="hotkey",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="core.hotkey"),
            preserve_default=False,
        ),
    ]
