# Generated by Django 4.2.15 on 2024-09-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_operator_email_remove_subnet_running_mainnet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="validatorinstance_status",
            field=models.BooleanField(default=False),
        ),
    ]
