# Generated by Django 4.2.16 on 2024-09-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_uploadedfile_user_uploadedfile_hotkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="subnet",
            name="code_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="github_repo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="hw_requirements",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="mainnet_netid",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="maintainers_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="owner_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="owner_nick",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="testnet_netid",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
