# Generated by Django 4.2.16 on 2024-10-08 01:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_subnet_hw_requirements"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subnet",
            old_name="hw_requirements",
            new_name="hardware_description",
        ),
        migrations.RenameField(
            model_name="subnet",
            old_name="mainnet_id",
            new_name="mainnet_netuid",
        ),
        migrations.RenameField(
            model_name="subnet",
            old_name="maintainers_ids",
            new_name="maintainer_discord_ids",
        ),
        migrations.RenameField(
            model_name="subnet",
            old_name="owner_id",
            new_name="owner_discord_id",
        ),
        migrations.RenameField(
            model_name="subnet",
            old_name="testnet_id",
            new_name="testnet_netuid",
        ),
        migrations.AddField(
            model_name="subnet",
            name="allowed_secrets",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="subnet",
            name="dumper_commands",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
